# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Koti"
  url = "/"
  weight = 10

[[main]]
  name = "Uutiset"
  url = "/post"
  weight = 20

[[main]]
  name = "Helluradio"
  url ="/radio"
  weight = 31

[[main]]
  name = "Tiimi"
  url ="/people"
  weight = 32

[[main]]
  name = "Ruokalista"
  url = "#ruokalista"
  weight = 33

[[main]]
  name = "Meistä"
  url = "/meista"
  weight = 45

[[main]]
  name = "Ota yhteyttä"
  url = "/#contact"
  weight = 50