appearance:
  theme_day: minimal
  theme_night: minimal
  font:
  font_size: L
day_night: true
seo:
  site_type: Organization
  local_business_type: ''
  org_name: ''
  description: ''
  twitter: ''
header:
  navbar:
    enable: false
highlight: false
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: false
  page: false
  post: false
  project: false
  publication: false
  talk: false
email: hellu@opkh.fi
phone: ''
address:
  street: Piertari Kalmin katu 7
  city: Helsinki
  region: ''
  postcode: '00560'
  country: Suomi
  country_code: FI
coordinates:
  latitude: '60.2037938'
  longitude: '24.9599621'
directions: 'Löydät meidät toisesta kerroksesta, yhteisöllisestä tilasta 204.'
office_hours: []
appointment_url: ''
contact_links:
  # - icon: map-marked-alt
  #   icon_pack: fas
  #   name: Reittiohjeet Google Maps
  #   link: >-
  #   https://www.google.com/maps/place/Helsingin+luonnontiedelukio/@60.2037938,24.9599621,17z/data=!3m1!4b1!4m6!3m5!1s0x4692091229a9c8c9:0xc333ce4ffea0062a!8m2!3d60.2037938!4d24.9625424!16s%2Fg%2F11v0zm6qb6?entry=ttu
  # - icon: bus-alt
  #   icon_pack: fas
  #   name: Reittiohjeet HSL
  #   link: >-
  #     https://reittiopas.hsl.fi/reitti/-/Helsingin%20luonnontiedelukio%2C%20K%C3%A4pyl%C3%A4%2C%20Helsinki%3A%3A60.210268%2C24.943388?arriveBy=false&locale=fi
  - icon: instagram
    icon_pack: fab
    name: 'Hellun OPKH:n Instagram'
    link: 'https://instagram.com/hellu_opkh'
  - icon: youtube
    icon_pack: fab
    name: 'Hellun OPKH:n Youtube kanava'
    link: 'https://www.youtube.com/channel/UCOU9UynKyFFVknD2-QG3lig'
address_format: fi  
main_menu:
  align: l
  show_logo: true
  highlight_active_link: true
  show_language: false
  show_day_night: true
  show_search: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  engine: 3
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: false
  commento:
    url: ''
search:
  provider: ''
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  engine: 0
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  microsoft_clarity: ''
cms:
  netlify_cms: true
  branch: master
icon:
  pack:
    ai: false
